import Head from "next/head";
import Image from "next/image";
import ChatSidebar from "../companants/ChatSidebar";
import styled from "styled-components";
import Leftbar from "../companants/Leftbar";
import HeaderTop from "../companants/HeaderTop";
import Chat from "../companants/Chat";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Glass>
          <Leftbar />
          <MainContainer>
            <HeaderTop />
            <FlexContainer>
              <ChatSidebar />
              <Chat />
            </FlexContainer>
          </MainContainer>
        </Glass>
      </Container>
    </div>
  );
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  background-color: #150c2e;
  :before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #3a8ad458;
    clip-path: circle(10% at center 10%);
  }
`;

const MainContainer = styled.div`
  width: 94%;
  height: 100%;
  display: flex;
  flex-direction: column;
`;

const FlexContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: flex-start;
  width: 100%;
  height: 90%;
`;

const Glass = styled.div`
  display: flex;
  width: 100%;
  height: 100%;
  background-color: transparent;
  backdrop-filter: blur(150px);
`;
